=== olgudz/Reversi/jars/Reversi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Variant">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Regular"/>
				<xs:enumeration value="Islands"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Computer"/>
				<xs:enumeration value="Human"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Position">
		<xs:complexType>
			<xs:attribute name="column" type="xs:byte" use="required"/>
			<xs:attribute name="row" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Players">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Player" maxOccurs="4"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Player">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Type"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Participant">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Position" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="number" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="InitialPositions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Participant" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GameType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Basic"/>
				<xs:enumeration value="MultiPlayer"/>
				<xs:enumeration value="DynamicMultiPlayer"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GameDescriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="GameType"/>
				<xs:element ref="Game"/>
				<xs:element ref="Players" minOccurs="0"/>
				<xs:element ref="DynamicPlayers" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Game">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Board"/>
				<xs:element ref="Variant"/>
				<xs:element ref="InitialPositions"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DynamicPlayers">
		<xs:complexType>
			<xs:attribute name="total-players" type="xs:byte" use="required"/>
			<xs:attribute name="game-title" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Board">
		<xs:complexType>
			<xs:attribute name="rows" type="xs:byte" use="required"/>
			<xs:attribute name="columns" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== olgudz/Reversi/source/UI/src/resources/ex2-islands-4-players.xml
<?xml version="1.0" encoding="UTF-8"?>
<GameDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Reversi.xsd">
	<GameType>MultiPlayer</GameType>
	<Game>
		<Board rows="8" columns="8"/>
		<Variant>Islands</Variant>
		<InitialPositions>
			<Participant number="1">
				<Position row="1" column="1"/>
			</Participant>
			<Participant number="2">
				<Position row="1" column="8"/>
			</Participant>
			<Participant number="3">
				<Position row="8" column="8"/>
			</Participant>
			<Participant number="4">
				<Position row="8" column="1"/>
			</Participant>
		</InitialPositions>
	</Game>
	<Players>
		<Player id="233">
			<Name>Mushon</Name>
			<Type>Human</Type>
		</Player>
		<Player id="143">
			<Name>Menash</Name>
			<Type>Human</Type>
		</Player>
		<Player id="456">
			<Name>Brurya</Name>
			<Type>Computer</Type>
		</Player>
		<Player id="583">
			<Name>Bilhaa</Name>
			<Type>Human</Type>
		</Player>
	</Players>
</GameDescriptor>

=== olgudz/Reversi/xml/ex2-small.xml
<?xml version="1.0" encoding="UTF-8"?>
<GameDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Reversi.xsd">
	<GameType>MultiPlayer</GameType>
	<Game>
		<Board rows="8" columns="8"/>
		<Variant>Regular</Variant>
		<InitialPositions>
			<Participant number="1">
				<Position row="4" column="4"/>
				<Position row="3" column="3"/>
			</Participant>
			<Participant number="2">
				<Position row="5" column="5"/>
			</Participant>
			<Participant number="3">
				<Position row="6" column="6"/>
			</Participant>
		</InitialPositions>
	</Game>
	<Players>
		<Player id="233">
			<Name>Mushon</Name>
			<Type>Human</Type>
		</Player>
		<Player id="143">
			<Name>Menash</Name>
			<Type>Human</Type>
		</Player>
		<Player id="456">
			<Name>Nachtze</Name>
			<Type>Computer</Type>
		</Player>
	</Players>
</GameDescriptor>
